Add plausible domain
IATI/iati-validator-docs pull request #10
Opened 2024-07-30 14:12 UTC by tillywoodfield

2024-08-26 14:22 UTC, Bjwebb requested changes

2024-08-26 14:22 UTC, Bjwebb commented on .python-version
> +3.12
I've discovered this is used by pyenv. If we keep this, then it should match the version in `.readthedocs.yml`

2024-09-03 12:05 UTC, tillywoodfield commented on .python-version
> +3.12
Yep it's for pyenv, I thought is would be useful to include in the same way that we have included `.nvmrc` in the javascript repos, if you're happy with that? I've updated it to be `3.10` as in `.readthedocs.yml`

2024-09-06 13:52 UTC, Bjwebb approved these changes

2024-09-06 13:54 UTC, Bjwebb commented on .python-version
> +3.12
Yes, I think that's fine to commit. I've actually started using pyenv recently, as my previous approach to specific python versions (deadsnakes ppa) isn't available on debian.

2024-09-06 13:56 UTC, merged